### ISSUE TITLE
[BUG] Error when collecting issue ages

### ISSUE THREAD

**Issue by philippjfr** [LaurenceMolloy/RepoDash#22]
When I run RepoDash on one of my projects I'm seeing some errors:

```
python RepoDash.py -u holoviz --repo holoviews -c 5
```

```
INFO Processing data...
[GithubIssues.py : get_issue_ages : 722] ERROR 12 'issues' table does not exist.


======== SQL EXCEPTION - START ========
('Timestamp subtraction must have the same timezones or no timezones', 'occurred at index opened_date')
========= SQL EXCEPTION - END =========

Traceback (most recent call last):
  File "src/RepoDash.py", line 98, in <module>
    gd.issue_ages.append(npa.values.flatten())
AttributeError: 'str' object has no attribute 'values'
```

The value of `npa` in this case is "unknown".

Debug info output:

<details>

```
DEBUG INFO
----------
commit: None
local timezone: CET
command line: RepoDash.py -u holoviz --repo holoviews -i
python: 3.7.6.final.0
python-bits: 64
OS: Darwin
OS-release: 18.5.0
Version: Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
requests: 2.22.0
pandas: 0.25.3
sqlalchemy: 1.3.12
numpy: 1.17.3
matplotlib: 3.1.2
```

</details>

**Comment by LaurenceMolloy** [comment]
Thanks for your feedback, Philip.
This bug is a Duplicate of #14.

The user that raised the original issue proposed a solution by submitting a pr (#15) to solve it. 

However, when I tested that pr for myself it broke my code, throwing the same error. I'll need to get to the bottom of this issue and find a generic solution that works for everyone. If you know anything about this (it's a timezone related issue) and can advise, I'd be grateful for the input.

In the meantime, you might be able to fix the issue in your copy of the code by making the following single-line edit (As shown in the PR - line number below is different to that shown in the PR due to further changes in the file since then):

Line 719 of RepoDash/src/GithubIssues.py:
`return result.applymap(lambda x: (pd.to_datetime(month_end_date, utc=True) - x).days)` 

For your convenience, as you've been able to provide me with your command line invocation I've produced a visual for you on my machine (see below)... I've presumed that you'll find the latest 12 months of metrics most useful (not just the latest 5 months of metrics that can be found in the earliest 10 pages of your issues - there are 43 pages of issues in all)

![2020-01-17-012206_1920x1080_scrot](https://user-images.githubusercontent.com/59101626/72577175-a3729980-38c9-11ea-85c7-cca95988ef19.png)

**Comment by philippjfr** [comment]
Thanks for the quick reply and sorry for not checking previous issues in more detail. I'll close as a duplicate.

**Comment by LaurenceMolloy** [comment]
No problem. Your environment may be useful context here in
understanding the issue.

Laurence

**Comment by LaurenceMolloy** [comment]
Hi Philipp,

Could I ask you for a bit of help here?

Can you test this change for me to see if it fixes the timezone issue you encountered?

Line 719 of RepoDash/src/GithubIssues.py:
`return result.applymap(lambda x: (pd.to_datetime(month_end_date, format='%Y-%m-%d', utc=False) - pd.to_datetime(x, format='%Y-%m-%d', utc=False)).days)`

As the calculation is a difference in terms of days, we don't require time at all. I think we may be more globally robust by removing timezone completely.

It works for me. I'm curious to know if it works for you as well.

Thanks
Laurence

**Comment by philippjfr** [comment]
@LaurenceMolloy Just tried it, that did not fix it for me (also I had to replace Line 725 not 719).

**Comment by philippjfr** [comment]
Ignore me on the line numbers, just realized I had patched some other stuff, which shifted the line numbers.

**Comment by LaurenceMolloy** [comment]
Thanks Philipp.

I've looked into this some more and realise that the database data is timezone aware. I've removed that awareness (simplified datetimes to YYYY-DD-MM, we're not interested in time level info anyway) and amended the code in get_issue_ages() again to ensure that the subtraction operands are always compatible regardless of database data awareness of timezone (doubly-defensive programming).

As this change is a little more involved, I've created a dev branch where you can pull the new GithubIssues.py file from to be sure that the code you're testing is identical to mine.

https://github.com/LaurenceMolloy/RepoDash/blob/dev/src/GithubIssues.py

Could you test this for me once more, using this new code file? Thanks.

**Comment by philippjfr** [comment]
@LaurenceMolloy That branch works for me, thanks for the fix! Great tool you're building here. I've presented the plots for all our packages to my team and I know @esc on the [numba](https://github.com/numba/numba) team is doing the same.

**Comment by esc** [comment]
@LaurenceMolloy indeed, thank you for this cool project. I got it running for Numba with the proposed one line fix. Here are the Numba plots:

![nuba_prs](https://user-images.githubusercontent.com/41563/72627502-efb2ed80-394c-11ea-9d8e-9dfc1e72afbe.png)
![numba_issues](https://user-images.githubusercontent.com/41563/72627503-f04b8400-394c-11ea-833d-e319987e1580.png)

**Comment by LaurenceMolloy** [comment]
Excellent. :D

Thanks for the feedback, Philipp. I've asked the OP of this issue to
confirm the same is true for him. If that's the case, I can close the
original issue as well.

Saw your feature request as well. Absolutely. Will get onto that. It ought
to be a simple yet useful enhancement to effect.

Laurence

**Comment by LaurenceMolloy** [comment]
Thankyou for the kind words, Valentin. It's heartening to know that folks
are finding this useful.

I've just looked up Numba. I may find that useful when building a Minecraft
server metrics dashboard for my son using RepoDash as both inspiration and
an architectural basis (see example below). Compiling the python would be a
pre-requisite if we decided to distribute it as a downloadable application.

Laurence
